services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: videogames
      MYSQL_PASSWORD: app
      MYSQL_USER: app
      MYSQL_ROOT_PASSWORD: app
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${MYSQL_DATABASE:-app}", "-U", "${MYSQL_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
 
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###